config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/loader_etude', to: 'pages#loader_etude'
  get '/saver_etude', to: 'pages#saver_etude'
  get '/loader_adherent', to: 'pages#loader_adherent'
  get '/saver_adherent', to: 'pages#saver_adherent'
  get '/test', to: 'pages#testing_page'
  post 'documents/generer', to: 'documents#generer' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :adherents
  resources :etudes do
    resources :phases
    resources :intervenants do
      resources :notation_intervenants
    end
  end

  resources :documents

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbardiv">
    <div class="logo"><%= render 'components/logo2' %></div>
    <div class="links">
        <a class="link" href="http://www.hex-agency.fr">Pour en apprendre plus sur HEX et nos service, rendez-vous sur notre site !</span>
    </div>
    <div class="btn-1"><%= link_to "Poste Vision", new_user_session_path, class: "txt"%></div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidenav">
  <div class="head">
    <%= render 'components/logo' %>
  </div>

  <div class="content">
    <a href="#"><div class="MainAction">Ressources Humaines</div></a>
    <%= link_to adherents_path do %><div class="SecAction">Gestion Etudiants</div><% end %>
    <a href="#"><div class="MainAction">Relations Clients</div></a>
    <%= link_to etudes_path do %><div class="SecAction">Gestion Etudes</div><% end %>
    <%= link_to etudes_path do %><div class="SecAction">Notation Interv</div><% end %>
    <%= link_to etudes_path do %><div class="SecAction">Sous-Traitants</div><% end %>
    <a href="#"><div class="MainAction">Configuration</div></a>
    <%= link_to documents_path do %><div class="SecAction">Documents Types</div><% end %>
  </div>



  <div class="foot">
    <div><%= link_to "Mon Compte", "#", :class => 'deco'%></div>
    <div><%= link_to "Déconnexion", destroy_user_session_path, method: :delete, :class => 'deco'%></div>
  </div>
  <div class="version">
    <div>Poste-Vision Beta 1.2</div>
  </div>
</div>