config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/loader_etude', to: 'pages#loader_etude'
  get '/saver_etude', to: 'pages#saver_etude'
  get '/loader_adherent', to: 'pages#loader_adherent'
  get '/saver_adherent', to: 'pages#saver_adherent'
  get '/test', to: 'pages#testing_page'
  post 'documents/generer', to: 'documents#generer' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :adherents
  resources :etudes do
    resources :phases
    resources :intervenants do
      resources :notation_intervenants
    end
  end

  resources :documents

end

app/models/adherent.rb
class Adherent < ApplicationRecord
  has_many :intervenants, dependent: :destroy

  validates :nom, presence: true, uniqueness: { scope: :prenom }
  validates :num_ba, presence: true, uniqueness: true
end

app/controllers/adherents_controller.rb
require "google_drive"

class AdherentsController < ApplicationController
  def index
    @adherents = Adherent.all.order(:nom)
  end

  def show
    @adherent = Adherent.find(params[:id])
    ba_document
  end

  def new
    @adherent = Adherent.new
  end

  def create
    @adherent = Adherent.new(adherent_params)
    if @adherent.save
      saving_adherent
      flash[:success] = "L'étudiant a été créé."
      redirect_to @adherent
    else
      flash[:error] = "Erreur d'execution"
      render 'new'
    end
  end

  def edit
    @adherent = Adherent.find(params[:id])
  end

  def update
    @adherent = Adherent.find(params[:id])
    if @adherent.update(adherent_params)
      saving_adherent
      flash[:success] = "L'étudiant a été mis à jour"
      redirect_to @adherent
    else
      flash[:error] = "Erreur d'execution"
      redirect_to adherents_path
    end
  end

  def destroy
    @adherent = Adherent.find(params[:id])
    if @adherent.destroy
      saving_adherent
      flash[:success] = "L'étudiant a été supprimé"
      redirect_to adherents_path
    else
      flash[:error] = "Erreur d'execution"
      redirect_to pages_path
    end
  end

  private

  def init_google_session
    @session = GoogleDrive::Session.from_service_account_key("config/google_config.json")
  end

  def adherent_params
    params.require(:adherent).permit(
      :prenom, :nom,
      :mail, :telephone, :num_ba,
      :adresse, :codepostal, :ville,
      :date_naissance, :numero_securite_social, :commune_naissance, :codepostal_naissance,
      :nom_banque, :iban, :bic,
      :annee_mandat, :campus, :pole, :poste,
      :demission, :alumni_ejc, :membre, :master,
      :cvec, :ba, :cotisation, :certificat_scolarite, :carte_vital, :carte_identite, :genre
    )
  end

  def saving_adherent
    init_google_session
    @ws = @session.spreadsheet_by_key("1noJZd6kty2Ib0345YhRhgrjDNA0SSXmOhhDbXPsl73M").worksheet_by_gid("1050525217")
    Adherent.all.each_with_index do |adherent, row|
      row += 2
      @ws[row, 1], @ws[row, 2], @ws[row, 3] = adherent.num_ba, adherent.prenom, adherent.nom
      @ws[row, 4], @ws[row, 5], @ws[row, 6] = %Q[="#{adherent.telephone}"], adherent.mail, adherent.num_ba
      @ws[row, 7], @ws[row, 8], @ws[row, 9] = adherent.adresse, adherent.codepostal, adherent.date_naissance
      @ws[row, 10], @ws[row, 11], @ws[row, 12] = adherent.numero_securite_social, adherent.commune_naissance, adherent.codepostal_naissance
      @ws[row, 13], @ws[row, 14], @ws[row, 15] = adherent.nom_banque, adherent.iban, adherent.bic
      @ws[row, 18], @ws[row, 19], @ws[row, 20] = adherent.cvec, adherent.certificat_scolarite, adherent.carte_vital
      @ws[row, 21], @ws[row, 23] = adherent.carte_identite, adherent.ba
      @ws[row, 24], @ws[row, 25], @ws[row, 26] = adherent.master, adherent.membre, adherent.alumni_ejc
      @ws[row, 27], @ws[row, 28], @ws[row, 29] = adherent.annee_mandat, adherent.campus, adherent.poste
      @ws[row, 30], @ws[row, 31], @ws[row, 32] = adherent.pole, adherent.nationalite, row
      @ws[row, 33], @ws[row, 34], @ws[row, 35] = adherent.ville, adherent.cotisation, adherent.demission
      @ws[row, 36] = adherent.genre
    end
    @ws.save
  end

  def ba_document
    @ba_params = {
      document_id: Document.find_by(nom: "BA"),
      change: [
        { title: "NumeroBA", content: @adherent.num_ba },
        { title: "PrenomNom", content: "#{@adherent.prenom} #{@adherent.nom}" },
        { title: "Mme/M", content: @adherent.genre },
        { title: "Adressepostale", content: @adherent.adresse },
        { title: "Cpville", content: "#{@adherent.codepostal} #{@adherent.ville}" },
        { title: "Numtelephone", content: @adherent.telephone },
        { title: "FaitLe", content: Date.today.strftime('%d/%m/%Y') }
      ]
    }
  end
end

app/views/adherents/edit.html.erb
<%= render 'adherents/shared/forms' %>

app/views/adherents/index.html.erb
<div class="main">
    <h1>Gestion des étudiants</h1>
    <%= link_to new_adherent_path do %>
        <div> Nouveau Adhérent <i class="fas fa-plus-circle"></i></div>
    <% end %>
    <div class="cartesEtu">
        <% @adherents.each do |adherent| %>
            <%= link_to adherent_path(adherent) do %>
                    <div class="carte">
                        <div class="titre">
                            <div class="texte">
                                <div><%= adherent.prenom %></div>
                                <div><%= adherent.nom %></div>
                            </div>
                            <div class="icone"><span><%= link_to adherent_path(adherent), method: :delete do %><i class="far fa-trash-alt delete"></i><% end %></span></div>
                        </div>
                        <div class="documents">
                            <% if adherent.cvec == true %><div class="docvert">cvec</div><% else %><div class="docrouge">cvec</div><% end %>
                            <% if adherent.carte_identite == true %><div class="docvert">ID</div><% else %><div class="docrouge">ID</div><% end %>
                            <% if adherent.carte_vital == true %><div class="docvert">CarteVitale</div><% else %><div class="docrouge">CarteVitale</div><% end %>
                            <% if adherent.certificat_scolarite == true %><div class="docvert">CertifScol</div><% else %><div class="docrouge">CertifScol</div><% end %>
                            <% if adherent.ba == true %><div class="docvert">BA</div><% else %><div class="docrouge">BA</div><% end %>
                            <% if adherent.cotisation == true %><div class="docvert">Cotisation</div><% else %><div class="docrouge">Cotisation</div><% end %>
                        </div>
                    </div>
            <% end %>
        <% end %>
    </div>

</div>

app/views/adherents/new.html.erb
<%= render 'adherents/shared/forms' %>

app/views/adherents/show.html.erb
<div class="main">
    <div class="container">
        <br>
        <span><%= link_to edit_adherent_path(@adherent) do %>Modifier les informations <i class="far fa-edit edit"></i><% end %></span>
		<span><%= link_to adherent_path(@adherent), method: :delete do %>Supprimer l'étudiant <i class="far fa-trash-alt delete"></i><% end %></span>
        <br>
        <span><%= link_to documents_generer_path(@ba_params), target: :_blank, method: :generer do %>Generer un BA <i class="fas fa-file"></i><% end %></span>
        <% # raise %>
        <br>
        <div> Prenom : <%= @adherent.prenom %></div> 
        <div> Nom : <%= @adherent.nom %></div>
        <div> Num BA : <%= @adherent.num_ba %></div>  
        <br>
        <div> Adresse Email : <%= @adherent.mail %></div> 
        <div> Telephone : <%= @adherent.telephone %></div> 
        <br>
        <div> Adresse Postale :<%= @adherent.adresse %></div> 
        <div> Code Postal : <%= @adherent.codepostal %></div> 
        <div> Ville : <%= @adherent.ville %></div> 
        <br>
        <div> Master : <%= @adherent.master %></div> 
        <br>
        <div> Date de Naissance : <%= @adherent.date_naissance %></div> 
        <div> Numero Securite Social : <%= @adherent.numero_securite_social %></div>
        <div> Nationalite : <%= @adherent.nationalite %></div>  
        <br>
        <div> Commune de Naissance : <%= @adherent.commune_naissance %></div> 
        <div> Code Postal de Naissance : <%= @adherent.codepostal_naissance %></div> 
        <br>
        <div> Nom Banque : <%= @adherent.nom_banque %></div> 
        <div> IBAN : <%= @adherent.iban %></div> 
        <div> BIC : <%= @adherent.bic %></div> 
        <br>
        <div> Carte d'Identité : <%= @adherent.carte_identite %></div> 
        <div> Carte Vitale : <%= @adherent.carte_vital %></div> 
        <div> Certificat de Scolarité : <%= @adherent.certificat_scolarite %></div> 
        <div> CVEC : <%= @adherent.cvec %></div> 
        <div> Bulletin d'Adhesion : <%= @adherent.ba %></div> 
        <div> cotisation : <%= @adherent.cotisation %></div> 
        <br>
        <div> membre : <%= @adherent.membre %></div> 
        <div> alumni : <%= @adherent.alumni_ejc %></div> 
        <div> demission : <%= @adherent.demission %></div> 
        <br>
        <div> année de mandat : <%= @adherent.annee_mandat %></div> 
        <div> campus : <%= @adherent.campus %></div> 
        <div> pole : <%= @adherent.pole %> </div> 
    </div>
</div>