config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/loader_etude', to: 'pages#loader_etude'
  get '/saver_etude', to: 'pages#saver_etude'
  get '/loader_adherent', to: 'pages#loader_adherent'
  get '/saver_adherent', to: 'pages#saver_adherent'
  get '/test', to: 'pages#testing_page'
  post 'documents/generer', to: 'documents#generer' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :adherents
  resources :etudes do
    resources :phases
    resources :intervenants do
      resources :notation_intervenants
    end
  end

  resources :documents

end

app/models/etude.rb
class Etude < ApplicationRecord
  has_many :phases, dependent: :destroy
  has_many :intervenants, through: :phases

  validates :references, presence: true, uniqueness: true
  validates :statut, presence: true
  validates :type_client, presence: true
  validates :prestation, presence: true
  validates :campus, presence: true
  validates :provenance, presence: true
  validates :date_demande, presence: true
end

app/controllers/etudes_controller.rb
require "google_drive"
@session = GoogleDrive::Session.from_credentials(JSON.parse(ENV.fetch('GOOGLE_API_CREDS')))

class EtudesController < ApplicationController
  def index
    @etudes = Etude.all.order(:references).reverse
  end

  def show
    @etude = Etude.find(params[:id])
    @phases = @etude.phases
    @intervenants = @etude.intervenants
  end

  def new
    @etude = Etude.new
  end

  def create
    @etude = Etude.new(etude_params)
    if @etude.save
      saving_etude
      flash[:success] = "L'étude a été créé."
      redirect_to @etude
    else
      flash[:error] = "Erreur d'execution"
      render 'new'
    end
  end

  def edit
    @etude = Etude.find(params[:id])
  end

  def update
    @etude = Etude.find(params[:id])
    if @etude.update(etude_params)
      saving_etude
      flash[:success] = "L'étude a été mis à jour"
      redirect_to etude_path(@etude)
    else
      flash[:error] = "Erreur d'execution"
      render 'edit'
    end
  end

  def destroy
    @etude = Etude.find(params[:id])
    if @etude.destroy
      saving_etude
      flash[:success] = "L'étude a été supprimé"
      redirect_to etudes_url
    else
      flash[:error] = "Erreur d'execution"
      redirect_to etudes_url
    end
  end

  private

  def init_google_session
    @session = GoogleDrive::Session.from_service_account_key("config/google_config.json")
  end

  def etude_params
    params.require(:etude).permit(
      :references, :nom, :type_client, :prestation, :provenance, :campus,
      :date_demande, :nom_client, :prenom_client, :appelation_client,
      :poste_client, :adresse, :codepostal, :ville, :mail, :telephone,
      :nbre_propcom, :nbre_convetu, :conv_cadre, :date_propcom, :date_convetu,
      :date_convcadre, :num_bdc, :budget_HT, :taux_marge, :nbre_av_je_methodo,
      :nbre_av_je_delais, :nbre_av_je_budget, :nbre_av_je_rupture, :nbre_av_je_rm,
      :nbre_av_client_methodo, :nbre_av_client_delais, :nbre_av_client_budget, :nbre_av_client_rupture,
      :nbre_av_client_rm, :frais_ht, :budget_total_ht, :budget_total_ttc, :statut, :data_debut_etude
    )
  end

  def saving_etude
    init_google_session
    @ws = @session.spreadsheet_by_key("1noJZd6kty2Ib0345YhRhgrjDNA0SSXmOhhDbXPsl73M").worksheet_by_gid("880104571")
    Etude.all.each_with_index do |etude, row|
      row += 2
      etude.date_demande.nil? ? @ws[row, 1] = "" : @ws[row, 1] = "#{etude.date_demande.year}#{etude.date_demande.month}"
      etude.date_convetu.nil? ? @ws[row, 2] = "" : @ws[row, 2] = "#{etude.date_convetu.year}#{etude.date_convetu.month}"
      @ws[row, 3] = etude.references
      @ws[row, 6], @ws[row, 7], @ws[row, 8], @ws[row, 9], @ws[row, 10] = etude.references, etude.nom, etude.type_client, etude.prestation, etude.provenance
      @ws[row, 11], @ws[row, 13], @ws[row, 14], @ws[row, 15] = etude.campus, etude.date_demande, etude.telephone, etude.mail
      @ws[row, 16], @ws[row, 17], @ws[row, 18], @ws[row, 19], @ws[row, 20] = etude.nbre_propcom, etude.date_propcom, etude.nbre_convetu, etude.date_convetu, etude.conv_cadre
      @ws[row, 21], @ws[row, 22], @ws[row, 23], @ws[row, 24] = etude.date_convcadre, etude.num_bdc, etude.budget_total_ht.to_i, etude.taux_marge
      @ws[row, 44], @ws[row, 45] = etude.frais_ht
      @ws[row, 49], @ws[row, 50] = etude.statut, etude.data_debut_etude
      @ws[row, 51] = row
      etude.date_convetu.nil? ? 0 : @ws[row, 52] = etude.date_convetu.mjd - etude.date_demande.mjd
    end
    @ws.save
  end
end

app/views/etudes/edit.html.erb
<%= render 'etudes/shared/forms' %>

app/views/etudes/index.html.erb
<div class="main">
    <h1>Gestion des études</h1>
    <%= link_to new_etude_path do %>
        <div> Nouveau etude <i class="fas fa-plus-circle"></i></div>
    <% end %>
    <div class="tableau">
        <div class="headline">
            <div class="colone"><%= "Référence" %></div>
            <div class="colone"><%= "Type" %></div>
            <div class="colone"><%= "Date CE/PC" %></div>
            <div class="colone"><%= "Statut" %></div>
            <div class="colone"><%= "Prestation" %></div>
            <div class="colone"><%= "Nbre Av" %></div>
            <div class="colone"><%= "JEH" %></div>
            <div class="colone"><%= "Budget HT" %></div>
            <div class="colone"><%= "Frais HT" %></div>
            <div class="colone"><%= "Budget Total" %></div>
        </div>
        <div class="mainline">
            <% @etudes.each do |etude| %>
                <%= link_to etude_path(etude) do %>
                        <div class="ligne">
                            <div class="colone"><%= etude.references %> <%= etude.nom %></div>
                            <div class="colone"><%= etude.type_client %></div>
                            <div class="colone"><%= etude.date_convetu %></div>
                            <div class="colone"><%= etude.statut %></div>
                            <div class="colone"><%= etude.prestation %></div>
                            <div class="colone"><%= "Nbre Av" %></div>
                            <div class="colone"><%= "JEH" %></div>
                            <div class="colone"><%= etude.budget_HT %></div>
                            <div class="colone"><%= etude.frais_ht %></div>
                            <div class="colone"><%= "Budget Total" %></div>
                        </div>
                <% end %>
            <% end %>
        </div>
    </div>

</div>

<% # raise %>

app/views/etudes/new.html.erb
<div class="main">
    <div class="container">
        <div class="formcontainer">
            <%= simple_form_for(@etude) do |f| %>
                <div class="formulaire">
                    <div class="Categorie">
                        <div class="Contenu">
                            <div class="Titre">Informations sur l'étude :</div>
                            <div class="part">
                                <div class="item3"><%= f.input :references %></div>
                                <div class="item3"><%= f.input :nom %></div>
                                <div class="item3"><%= f.input :date_demande, as: :date, html5: true, label: "Date de la demande d'étude :" %></div>
                            </div>
                            <div class="part">
                                <div class="item3"><%= f.input :type, as: :select, collection: ["Grand Groupe", "PME", "Entrepreneur", "J.E.", "Association", "Start-up"], label: "Type de client :"  %></div>
                                <div class="item3"><%= f.input :prestation, as: :select, collection: ["Etude de marché", "Etude d'image", "Etude de satisfaction", "Clients Mystère", "Business Plan", "Plan de communication", "Sous traitance", "Autre"], label: "Prestation :"  %></div>
                                <div class="item3"><%= f.input :campus, as: :select, collection: ["Paris", "Angers", "Bordeaux", "Lyon"]  %></div>
                            </div>
                            <div class="Titre">Contacts du client :</div>
                            <div class="part">
                                <div class="item2"><%= f.input :mail, label: "Adresse electronique :" %></div>
                                <div class="item2"><%= f.input :telephone, label: "Téléphone :" %></div>
                            </div>
                            <div class="Titre">Informations sur le client :</div>
                            <div class="part">
                                <div class="item4"><%= f.input :appelation_client, as: :select, collection: ["Monsieur", "Madame"]  %></div>
                                <div class="item4"><%= f.input :prenom_client, label: "Prenom du client :" %></div>
                                <div class="item4"><%= f.input :nom_client, label: "Nom du client :" %></div>
                                <div class="item4"><%= f.input :poste_client, label: "Poste du client :" %></div>
                            </div>
                            <div class="Titre">Adresse de l'entreprise :</div>
                            <div class="part">
                                <div class="item3"><%= f.input :adresse, label: "Adresse de l'entreprise :" %></div>
                                <div class="item3"><%= f.input :codepostal, label: "Code Postal :" %></div>
                                <div class="item3"><%= f.input :ville, label: "Ville :" %></div>
                            </div>
                            <div class="Titre">Proposition commerciale :</div>
                            <div class="part">
                                <div class="item4"><%= f.input :nbre_propcom, label: "Nombre P.C." %></div>
                                <div class="item4"><%= f.input :nbre_convetu, label: "Nombre C.E." %></div>
                                <div class="item4"><%= f.input :conv_cadre, as: :boolean, checked_value: true, unchecked_value: false, label: "Convention Cadre", label: "" %></div>
                                <div class="item4"><%= f.input :num_bdc, label: "Numéro de B.d.C." %></div>
                            </div>
                            <div class="part">
                                <div class="item3"><%= f.input :date_propcom, as: :date, html5: true, label: "Date d'envoie de la P.C." %></div>
                                <div class="item3"><%= f.input :date_convetu, as: :date, html5: true, label: "Date de signature de la C.E." %></div>
                                <div class="item3"><%= f.input :date_convcadre, as: :date, html5: true, label: "Date de signature de la C.C." %></div>
                            </div>
                            <div class="Titre">Avenants imputables à la junior :</div>
                            <div class="part">
                                <div class="item5"><%= f.input :nbre_av_je_methodo, html5: true, label: "Nbre av méthodologie" %></div>
                                <div class="item5"><%= f.input :nbre_av_je_delais, html5: true, label: "Nbre av délais" %></div>
                                <div class="item5"><%= f.input :nbre_av_je_budget, html5: true, label: "Nbre av budget" %></div>
                                <div class="item5"><%= f.input :nbre_av_je_rupture, html5: true, label: "Nbre av rupture" %></div>
                                <div class="item5"><%= f.input :nbre_av_je_rm, html5: true, label: "Nbre av au RM" %></div>
                            </div>
                            <div class="Titre">Avenants imputables au Client :</div>
                            <div class="part">
                                <div class="item5"><%= f.input :nbre_av_client_methodo, html5: true, label: "Nbre av méthodologie" %></div>
                                <div class="item5"><%= f.input :nbre_av_client_delais, html5: true, label: "Nbre av délais" %></div>
                                <div class="item5"><%= f.input :nbre_av_client_budget, html5: true, label: "Nbre av budget" %></div>
                                <div class="item5"><%= f.input :nbre_av_client_rupture, html5: true, label: "Nbre av rupture" %></div>
                                <div class="item5"><%= f.input :nbre_av_client_rm, html5: true, label: "Nbre av RM" %></div>
                            </div>
                            <div class="Titre">Budget et frais :</div>
                            <div class="part">
                                <div class="item5"><%= f.input :budget_HT, label: "Budget phases HT" %></div>
                                <div class="item5"><%= f.input :taux_marge, label: "Taux de marge" %></div>
                                <div class="item5"><%= f.input :frais_ht, label: "Frais HT" %></div>
                                <div class="item5"><%= f.input :budget_total_ht, label: "Budget total HT" %></div>
                                <div class="item5"><%= f.input :budget_total_ttc, label: "Budget total TTC" %></div>
                            </div>
                            <div class="Titre">Statut de l'étude :</div>
                            <div class="part">
                                <div class="item2"><%= f.input :statut, as: :select, collection: ["Avortée", "Signé", "Stand By", "En cours"], label: "Statut de l'étude :"  %></div>
                                <div class="item2"><%= f.input :data_debut_etude, as: :date, html5: true, label: "Date de début d'étude :" %></div>
                            </div>
                        </div>
                    </div>
                    <%= f.submit "Creer un Etude", id: "Creation" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

    
    

    

    

    

app/views/etudes/show.html.erb
<div class="main">
    <div class="mise_en_page1">
        <div class="title">
            <div class="titre"><%= @etude.references %> - <%= @etude.nom %>
            </div>
            <span><%= link_to edit_etude_path(@etude) do %><i class="far fa-edit edit"></i><% end %></span>
            <span><%= link_to etude_path(@etude), method: :delete do %><i class="far fa-trash-alt delete"></i><% end %></span>
        </div>

        <div class="bigcartes">
            <div class="partcarte">
                <div class="bigcarte">
                    <div class="titre">
                        <div class="texte"><i class="fas fa-info-circle"></i> Informations sur l'étude</div>
                    </div>
                    <div class="content">
                        <div class="texte"><i class="fas fa-id-card"></i>Reference : <%= @etude.references %><% unless @etude.num_bdc.nil? %><div>, Numéro de BdC :<%= @etude.num_bdc %></div> <% end %> </div>
                        <div class="texte"><i class="fas fa-building"></i>Entreprise : <%= @etude.nom %></div>
                        <div class="texte"><i class="fas fa-list-ul"></i>Type de prestation : <%= @etude.prestation %></div>
                        <div class="texte"><i class="fas fa-calendar-day"></i>Date de la demande : <%= @etude.date_demande %></div>
                        <div class="texte"><i class="fas fa-city"></i>Campus en charge : <%= @etude.campus %> </div>
                        <div class="texte"><i class="fas fa-city"></i>Provenance : <%= @etude.provenance %> </div>
                    </div>
                </div>

                <div class="bigcarte">
                    <div class="titre">
                        <div class="texte"><i class="fas fa-money-bill-alt"></i> Budget de l'étude</div>
                    </div>
                    <div class="content">
                        <div class="texte"><i class="fas fa-shopping-cart"></i>Budget HT : <%= @etude.budget_HT %></div>
                        <div class="texte"><i class="fas fa-funnel-dollar"></i>Frais HT : <%= @etude.frais_ht %> </div>
                        <div class="texte"><i class="fas fa-money-check-alt"></i>Budget Total HT : <%= @etude.budget_total_ht %></div>
                        <div class="texte"><i class="fas fa-receipt"></i>Budget Total TTC : <%= @etude.budget_total_ttc %></div>
                        <div class="texte"><i class="fas fa-hand-holding-usd"></i>Taux de marge : <%= @etude.taux_marge %></div>
                    </div>
                </div>
            </div>

            <div class="partcarte">
                <div class="bigcarte">
                    <div class="titre">
                        <div class="texte"><i class="fas fa-money-bill-alt"></i> Statut de l'étude</div>
                    </div>
                    <div class="content">
                        <div class="texte"><i class="fas fa-play"></i>Statut : <%= @etude.statut %></div>
                        <div class="texte"><i class="fas fa-calendar-day"></i>Date de début : <%= @etude.data_debut_etude %>  </div>
                    </div>
                </div>

                <div class="bigcarte">
                    <div class="titre">
                        <div class="texte"><i class="fas fa-user-tie"></i> Informations sur le client</div>
                    </div>
                    <div class="content">
                        <div class="texte"><i class="fas fa-id-card"></i>Nom du client : <%= @etude.appelation_client %> <%= @etude.prenom_client %>  <%= @etude.nom_client %></div>
                        <div class="texte"><i class="fas fa-at"></i>Mail : <%= @etude.mail %>  </div>
                        <div class="texte"><i class="fas fa-phone"></i>Telephone : <%= @etude.telephone %></div>
                        <div class="texte"><i class="fas fa-user-tag"></i>Poste : <%= @etude.poste_client %></div>
                        <div class="texte"><i class="fas fa-building"></i>Type d'entreprise : <%= @etude.type_client %></div>
                        <div class="texte"><i class="fas fa-map-marked-alt"></i>Adresse courrier : <%= @etude.adresse %></div>
                        <div class="texte"><i class="fas fa-map-marked-alt"></i>Code Postal, Ville : <%= @etude.codepostal %> <%= @etude.ville %></div>
                    </div>
                </div>
            </div>

            <div class="partcarte">
                <div class="bigcarte">
                    <div class="titre">
                        <div class="texte"><i class="fas fa-file-signature"></i> Informations Contractuelles</div>
                    </div>
                    <div class="content">
                        <div class="texte"><i class="fas fa-sort-numeric-up-alt"></i>Nombre de PC envoyés : <%= @etude.nbre_propcom %></div>
                        <div class="texte"><i class="fas fa-calendar-check"></i>Date de la première PC : <%= @etude.date_propcom %></div>
                        <div class="texte"><i class="fas fa-signature"></i>Nombre de CE/BdC envoyés : <%= @etude.nbre_convetu %></div>
                        <div class="texte"><i class="fas fa-calendar-check"></i>Date de signature : <%= @etude.date_convetu %></div>
                        <div class="texte"><i class="fas fa-handshake"></i>Etude sous convention cadre : <%= @etude.conv_cadre ? "Oui" : "Non" %></div>
                        <div class="texte"><i class="fas fa-calendar-check"></i>Date signature de la convention cadre : <%= @etude.date_convcadre %></div>
                    </div>
                </div>

                <div class="bigcarte">
                    <div class="titre">
                        <div class="texte"><i class="fas fa-hard-hat"></i> Avenants</div>
                    </div>
                    <div class="content">
                        <div class="tableau">
                            <div class="headligne">
                                <div class="mcolone">Imputables</div>
                                <div class="colone">junior</div>
                                <div class="colone">Client</div>
                            </div>
                            <div class="mainligne">
                                <div class="mcolone">Methodologie</div>
                                <div class="colone"><%= @etude.nbre_av_je_methodo %></div>
                                <div class="colone"><%= @etude.nbre_av_client_methodo %></div>
                            </div>
                            <div class="mainligne">
                                <div class="mcolone">Délais</div>
                                <div class="colone"><%= @etude.nbre_av_je_delais %></div>
                                <div class="colone"><%= @etude.nbre_av_client_delais %></div>
                            </div>
                            <div class="mainligne">
                                <div class="mcolone">Budget</div>
                                <div class="colone"><%= @etude.nbre_av_je_budget %></div>
                                <div class="colone"><%= @etude.nbre_av_client_budget %></div>
                            </div>
                            <div class="mainligne">
                                <div class="mcolone">Rupture</div>
                                <div class="colone"><%= @etude.nbre_av_je_rupture %></div>
                                <div class="colone"><%= @etude.nbre_av_client_rupture %></div>
                            </div>
                            <div class="mainligne">
                                <div class="mcolone">RM</div>
                                <div class="colone"><%= @etude.nbre_av_je_rm %></div>
                                <div class="colone"><%= @etude.nbre_av_client_rm %></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>



            <% # raise %>
        
        <div class="partphase">
            <div class="titre">Phases de l'étude :</div>
            <div class="cartesPhase">
                <% @phases.each do |phase| %>
                    <div class="carte">
                        <div class="phase">
                            <div class="titre">
                                <div class="texte"><%= phase.nom %></div>
                                <div class="icone">
                                    <span><%= link_to edit_etude_phase_path(@etude, phase) do %><div><i class="far fa-edit edit"></i></div><% end %></span>
                                    <span><%= link_to etude_phase_path(@etude, phase), method: :delete do %><i class="far fa-trash-alt delete"></i><% end %></span>
                                </div>
                            </div>
                            <div class="content">
                                <div class="texte"><i class="far fa-calendar-alt"></i>Du <% if phase.date_debut.nil? %> <%= "N/A" %> <% else %><%= phase.date_debut.strftime("%d/%m/%Y") %> <% end %>au<% if phase.date_fin.nil? %> <%= "N/A" %> <% else %><%= phase.date_fin.strftime("%d/%m/%Y") %><% end %></div>
                                <div class="texte">Nbre Intervenants : <%= phase.nbre_interv %></div>
                                <div class="texte">Nbre JEH/interv : <%= phase.nbre_jeh_indiv %></div>
                                <div class="texte">Indemnisation/interv : <%= phase.remuneration %> €</div>
                                <div class="texte">Budget HT : <%= phase.budget_ht %> €</div>
                                <div class="texte">PVR : <%= phase.pvr.nil? || phase.pvr == false ? "Non" : " Oui"%>,  Facture : <%= phase.facture.nil? || phase.facture == false ? "Non" : " Oui"%></div>
                            </div>
                        </div>
                    </div>
                <% end %>
                <div class="carte">
                    <%= link_to new_etude_phase_path(@etude) do %>
                        <div class="new">
                            <div class="icon">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="partphase">
            <div class="titre">Intervenants sur l'étude :</div>
            <div class="cartesPhase">
                <% @intervenants.each do |intervenant| %>
                    <%= link_to etude_intervenant_path(@etude, intervenant) do%>
                        <div class="carte">
                            <div class="phase">
                                <div class="titre">
                                    <div class="texte"><%= intervenant.adherent.prenom %></div>
                                    <div class="icone">
                                        <span><%= link_to etude_intervenant_path(@etude, intervenant) do %><i class="far fa-trash-alt delete"></i><% end %></span>
                                    </div>
                                </div>
                                <div class="titre">
                                    <div class="texte"><%= intervenant.adherent.nom %></div>
                                </div>
                                <div class="content">
                                    <div class="texte">Phase : <%= intervenant.phase.nom %></div>
                                    <div class="texte"><i class="far fa-calendar-alt"></i>Du <% if intervenant.phase.date_debut.nil? %> <%= "N/A" %> <% else %><%= intervenant.phase.date_debut.strftime("%d/%m/%Y") %> <% end %>au <% if intervenant.phase.date_fin.nil? %> <%= "N/A" %> <% else %><%= intervenant.phase.date_fin.strftime("%d/%m/%Y") %><% end %></div>
                                    <div class="texte">JEH : <%= intervenant.phase.nbre_jeh_indiv %></div>
                                    <div class="texte">Indemnisation : <%= intervenant.phase.remuneration %> €</div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
                <div class="carte">
                    <%= link_to new_etude_intervenant_path(@etude) do %>
                        <div class="new">
                            <div class="icon">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

    </div>
</div>

<% # raise %>